### ISSUE TITLE
persist data?

### ISSUE THREAD

**Issue by lonnietc** [abrahamjoc/docker-compose-kong-konga#1]
Hello,

I have just used your docker-compose kong-konga to setup and run a Kong gateway instance for testing to learn about it more as well as to learn more about docker-compose.

I have noticed that if I do a "docker-compose down" then I lose all of my settings and information when I bring it back up the next time with "docker-compose up -d".

Is there a way to persist the data within with the used volume or mapped to the host?
Thanks in advance

**Comment by abrahamjoc** [comment]
Hi,

I have maked refactor of code for persisting data.

Now the pgsql data will save in a folder call `dbdata`.

This is for:

>  the use case in that you down docker-composer and up again.

**Comment by lonnietc** [comment]
Hello,

Does this now mean that Konga will also persist the data inside postgresql as well?

That was the problem that I was having in I would bring up everything with "docker compose up", access Konga on port 1337, make an admin account, add some services and routes, and then logout. but when I brought everything down with "docker-compose down" then later upon restarting the whole assembly again with "docker-compose up" again, then all of my settings in Konga were gone and I have to re-enter them once again.

It's the Konga data that I need to persist as well as the Kong data.
Thanks

**Comment by abrahamjoc** [comment]
Hi,

I have maked a new push.

Now the konga data will save in a folder call `kongadata`.

**Comment by lonnietc** [comment]
Thanks so very much as it looks like it is holding the Konga data now.

I will now try to do some more testing but it is looking good so far.

Cheers
