### ISSUE TITLE
How to add letsencrypt container

### ISSUE THREAD

**Issue by lonnietc** [abrahamjoc/docker-compose-kong-konga#2]
Hello,

The docker-compose.yml files seems to run well, but I am still trying to determine why it does not persist the data.

In any case, I would like to add in SSL encryption for the server that I have it running on and was wondering how to add in a Letsencrypt container to work with Kong and Konga?

Any suggestions?

**Comment by abrahamjoc** [comment]
Hi, If you need to add SSL Encryption on your connection, I recommend you to see those topic:

**Kong**: https://docs.konghq.com/1.0.x/proxy/#configuring-ssl-for-a-route

**Konga**: https://github.com/pantsel/konga/issues/245

**Comment by lonnietc** [comment]
Thanks and  I will look into it more as well once I have the Konga and Kong data both being saved either on the host filesystem or within a volume.

I added a message to the other post on persisting the data but as it was closed already, I do not know if you will get it to be able to reply.

Thanks

**Comment by abrahamjoc** [comment]
For **Konga** I recommend you to see: https://github.com/pantsel/konga#environment-variables

It's exist `SSL_KEY_PATH` and `SSL_CRT_PATH`.

In this case, you should create a new container image with your SSL files, or add as env secrets or volumes config.
